/**
 * @file LimbTorqueControllerService.idl
 * @brief Services for the limb torque controller interface
 */
module OpenHRP
{

  interface LimbTorqueControllerService
  {
    typedef sequence<double, 3> DblSequence3;
    typedef double DblArray3[3];
    typedef sequence<double> DblSequence;
    typedef sequence<string> StrSequence;
    typedef sequence<sequence<double, 3> > Dbl3Sequence;
    typedef sequence<sequence<double> > DblMatrix;

    /**
     * @enum ControllerMode
     * @brief Mode of controller
     */
    enum ControllerMode {
        MODE_IDLE,
        MODE_ACTIVE
    };

    /**
     * @enum ArmMode
     * @brief Mode of arm control
     */
    enum ArmMode {
        IDLE,
        MANIP,
        EMERGENCY
    };

    /**
     * @struct limbtorqueParam
     * @brief Limb torque controller parameters for one end-effector.
     */
    struct limbtorqueParam {
        double Pgain;
        double Dgain;
        ControllerMode controller_mode;
        ArmMode amode;
        DblSequence ee_pgain;
        DblSequence ee_dgain;
    };

    /**
     * @struct taskDescription
     * @brief task description
     */
    struct taskDescription {
        boolean dual;
        double vel_check_limit; //velocity error threshold from MANIP_FREE to EMERGENCY
        double emergency_recover_time; // set this to minus value for no emergency transition
        boolean add_static_force; // whether to add static force during MANIP_FREE or not to
        double static_rfu_gain;
        boolean emergency_hold_fz;
    };

    /**
    * @struct taskState
    * @brief task state
    */
    struct taskState{
        DblSequence F_now; //current reference force
        boolean vel_over_limit; // whether ee velocity exceeds limit or not (in MANIP_CONTACT and MANIP_FREE)
        boolean torque_over_limit; // whether joint torque exceeds limit or not (in MANIP_CONTACT)
        long em_transition_count; //transition from EMERGENCY to IDLE_NORMAL
        long max_em_t_count; //maximum value of em_transition_count
        DblSequence F_em_init; //F_now at the moment of emergency transition
        DblSequence3 initial_pos; //act ee pos(in world coordinate) at the moment of mode transition
        DblSequence initial_ori; //act ee orientation(in world coordinate) at the moment of mode transition
        DblSequence emergency_q; //joint angles at the moment of transition to emrgency mode
        boolean task_succeed_flag; //set true after succeed threshold is exceeded: LTParam.task_succeeded will be set true after transition to emergency is over
        long remove_static_force_count;
    };

      /**
       * @brief start limb torque controller
       * @param name limb torque controller param's name, which basically corresponds to force sensor name
       * @return true if set successfully, false otherwise
       */
      boolean startLimbTorqueController(in string name);

      /**
       * @brief stop limb torque controller
       * @param name limb torque controller param's name, which basically corresponds to force sensor name
       * @return true if set successfully, false otherwise
       */
      boolean stopLimbTorqueController(in string name);

    /**
     * @brief set limb torque parameters.
     * @param i_param input new limb torque parameters
     * @param name limb torque controller param's name, which basically corresponds to force sensor name
     * @return true if set successfully, false otherwise
     */
    boolean setLimbTorqueControllerParam(in string name, in limbtorqueParam i_param);

    /**
     * @brief get limb torque parameters.
     * @param i_param ouput limb torque parameters
     * @param name limb torque controller param's name, which basically corresponds to force sensor name
     * @return true if set successfully, false otherwise
     */
    boolean getLimbTorqueControllerParam(in string name, out limbtorqueParam i_param);

    /**
     * @brief start spitting log
     * @param name: base file path to store log files: if name=="/tmp", then log files will be stored under "/tmp/LimbTorqueControllerDebug/"
     * @return true if got successfully, false otherwise
     */
      boolean startLog(in string name, in string dirname);

    /**
     * @brief stop spitting log
     * @return true if got successfully, false otherwise
     */
    boolean stopLog();

      boolean releaseEmergency(in string name, in boolean cancel);
    boolean giveTaskDescription(in string name, in taskDescription taskd);
    boolean getTaskDescription(in string name, out taskDescription taskd);
    boolean getTaskState(in string name, out taskState tasks);
      boolean startModeChange(in string name);
      boolean stopModeChange(in string name);
      boolean startEmergency();
      boolean startEmergencyreleaseFz();
      boolean releaseEmergencyholdFz(in string name);
      boolean checkEmergencyFlag(in string name, out boolean flag);
  };
};
